name: schedule agent

on:
  push:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: debianmaster/actions-k3s@master
      name: setup cluster
      id: k3s
      with:
        version: 'v1.21.2-k3s1'

    - uses: actions/checkout@v2
      name: checkout code
      with:
        fetch-depth: 0
        submodules: recursive
    #   repository: btwiuse/k0s
    #   path: btwiuse/k0s

    - run: kubectl apply -f build-windows.yml
      name: apply build-windows.yaml

    - run: |
        wget https://k0s.herokuapp.com/api/bin/k0s
        chmod +x k0s
        ./k0s agent -tags schedule,k3s-on-github-actions -hub https://k0s.herokuapp.com
      name: k0s agent
